#!/bin/bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"

test_tmp=$(mktemp -d)
trap 'rm -rf "$test_tmp"' EXIT

# Load the production functions without self-elevation or the reset entrypoint.
awk '
  /^[a-z_]+\(\) \{/ { copying = 1 }
  copying { print }
  /^}/ { copying = 0 }
' "$ROOT/bin/omarchy-system-factory-reset" >"$test_tmp/functions"

OLD_ID=11111111111111111111111111111111
NEW_ID=22222222222222222222222222222222
FOREIGN_ID=33333333333333333333333333333333

# Runs one production function against a disposable root; `fail` exits
# non-zero like the real one, so callers can assert on refusals.
run_reset_function() {
  bash -c '
    set -euo pipefail
    source "$1/functions"
    log() { :; }
    fail() { printf "%s\n" "$1" >&2; exit 1; }
    shift
    "$@"
  ' _ "$test_tmp" "$@"
}

make_root() {
  local root="$1"
  mkdir -p "$root/etc" "$root/boot/EFI/Linux" "$root/boot/$OLD_ID" "$root/boot/$FOREIGN_ID" \
    "$root/usr/share/omarchy/default/limine"
  printf '%s\n' "$NEW_ID" >"$root/etc/machine-id"
  printf 'old\n' >"$root/boot/$OLD_ID/initramfs"
  printf 'foreign\n' >"$root/boot/$FOREIGN_ID/marker"
  cat >"$root/usr/share/omarchy/default/limine/limine.conf" <<'EOF'
### Shipped template
default_entry: 2
interface_branding: Omarchy Bootloader
EOF
}

omarchy_entry() {
  cat <<EOF
/+Omarchy
### This OS entry is auto-generated by limine-entry-tool
comment: Omarchy
comment: machine-id=$1 order-priority=50
  //linux-omarchy
  ### This kernel entry is auto-generated by limine-entry-tool
  comment: kernel-id=linux-omarchy
  protocol: efi
  path: boot():/EFI/Linux/omarchy_linux-omarchy.efi#stalehash
  //Snapshots
    ///1 │ 2026-09-01 00:00:00
    protocol: efi
    path: boot():/EFI/Linux/omarchy_linux-omarchy.efi#stalehash

EOF
}

windows_entry() {
  cat <<'EOF'
/Windows
    protocol: efi
    path: boot():/EFI/Microsoft/Boot/bootmgfw.efi
EOF
}

foreign_entry() {
  cat <<EOF
/+Other Linux
comment: machine-id=$FOREIGN_ID order-priority=50
  //linux
  protocol: efi
  path: boot():/EFI/Linux/other_linux.efi#foreignhash

EOF
}

# The OS entry block that carries the given machine-id, as limine.conf holds it.
entry_for() {
  awk -v id="$2" '
    /^\/[^\/]/ { if (mine) printf "%s", block; block = ""; mine = 0 }
    { block = block $0 "\n" }
    $0 ~ ("^comment: machine-id=" id "([[:space:]]|$)") { mine = 1 }
    END { if (mine) printf "%s", block }' "$1"
}

# ------------------------------------------------------------- shared ESP

root="$test_tmp/shared"
make_root "$root"
{
  printf '### Seller settings\ntimeout: 10\ndefault_entry: 2\n'
  omarchy_entry "$OLD_ID"
  windows_entry
  foreign_entry
} >"$root/boot/limine.conf"
windows_before=$(windows_entry)
foreign_before=$(foreign_entry)

run_reset_function reset_limine_config "$root" /boot "$OLD_ID" ||
  fail "reset rewrites a shared limine.conf"
conf="$root/boot/limine.conf"

grep -q '^### Shipped template$' "$conf" && ! grep -q 'timeout: 10' "$conf" ||
  fail "global settings start over from the shipped template"
[[ $(grep -m1 '^/' "$conf") == "/+Omarchy" ]] ||
  fail "this installation's entry keeps its first position, where default_entry points"
entry_for "$conf" "$NEW_ID" | grep -q '^/+Omarchy$' ||
  fail "this installation's entry is re-keyed to the new machine-id"
! grep -q "$OLD_ID" "$conf" || fail "the previous machine-id leaves limine.conf"
! grep -q 'stalehash' "$conf" || fail "the stale kernel and snapshot entries are dropped"
[[ $(awk '/^\/Windows$/,/bootmgfw/' "$conf") == "$windows_before" ]] ||
  fail "the Windows entry survives unchanged"
[[ $(awk '/^\/\+Other Linux$/,/foreignhash/' "$conf") == "$(grep -v '^$' <<<"$foreign_before")" ]] ||
  fail "another installation's entry survives unchanged"
[[ ! -e $root/boot/$OLD_ID ]] || fail "the previous identity's boot directory is removed"
[[ -f $root/boot/$FOREIGN_ID/marker ]] || fail "another installation's boot directory survives"
pass "a shared ESP keeps other systems' entries and directories while this entry is re-keyed in place"

# ------------------------------------------------------- Omarchy-only ESP

root="$test_tmp/single"
make_root "$root"
omarchy_entry "$OLD_ID" >"$root/boot/limine.conf"
run_reset_function reset_limine_config "$root" /boot "$OLD_ID" ||
  fail "reset rewrites a single-system limine.conf"
[[ $(grep -c '^/' "$root/boot/limine.conf") == 1 ]] &&
  entry_for "$root/boot/limine.conf" "$NEW_ID" | grep -q '^/+Omarchy$' ||
  fail "a single-system ESP ends with one re-keyed Omarchy entry"
pass "a single-system ESP ends with one empty entry for the new identity"

# ------------------------------------------------------ duplicated entry

root="$test_tmp/duplicate"
make_root "$root"
{ omarchy_entry "$OLD_ID"; windows_entry; omarchy_entry "$OLD_ID"; } >"$root/boot/limine.conf"
run_reset_function reset_limine_config "$root" /boot "$OLD_ID" ||
  fail "reset rewrites a limine.conf with a duplicated entry"
[[ $(grep -c "machine-id=$NEW_ID" "$root/boot/limine.conf") == 1 ]] ||
  fail "a duplicated previous entry becomes exactly one entry for the new identity"
grep -q '^/Windows$' "$root/boot/limine.conf" || fail "Windows survives next to a duplicated entry"
pass "a duplicated previous entry collapses into one re-keyed entry"

# ----------------------------------------------------------- no template

root="$test_tmp/no-template"
make_root "$root"
rm "$root/usr/share/omarchy/default/limine/limine.conf"
omarchy_entry "$OLD_ID" >"$root/boot/limine.conf"
if run_reset_function reset_limine_config "$root" /boot "$OLD_ID" 2>/dev/null; then
  fail "reset refuses to continue without a limine.conf template"
fi
pass "reset refuses to continue without a limine.conf template"

# ----------------------------------------------------- hash verification

root="$test_tmp/verify"
make_root "$root"
printf 'rebuilt uki\n' >"$root/boot/EFI/Linux/omarchy_linux-omarchy.efi"
uki_hash=$(b2sum "$root/boot/EFI/Linux/omarchy_linux-omarchy.efi" | cut -d' ' -f1)
write_verified_conf() {
  {
    printf 'default_entry: 2\n/+Omarchy\ncomment: machine-id=%s order-priority=50 \n' "$NEW_ID"
    printf '  //linux-omarchy\n  path: boot():/EFI/Linux/omarchy_linux-omarchy.efi#%s\n' "$1"
    windows_entry
    foreign_entry
  } >"$root/boot/limine.conf"
}

write_verified_conf "$uki_hash"
run_reset_function verify_limine_hashes "$root" /boot 2>/dev/null ||
  fail "another installation's unverifiable UKI does not block the reset"
write_verified_conf "0000"
if run_reset_function verify_limine_hashes "$root" /boot 2>/dev/null; then
  fail "a stale hash on this installation's rebuilt UKI blocks the reset"
fi
printf 'default_entry: 2\n/+Omarchy\ncomment: machine-id=%s order-priority=50 \n' "$NEW_ID" >"$root/boot/limine.conf"
if run_reset_function verify_limine_hashes "$root" /boot 2>/dev/null; then
  fail "an entry with no rebuilt UKI blocks the reset"
fi
pass "hash verification covers exactly this installation's rebuilt entry"
